# Daily Waffle grids for testing

test_grids = [
    {
        "0-5": {"type": "g", "letter": "g"},
        "0-6": {"type": "w", "letter": "g"},
        "0-7": {"type": "y", "letter": "s"},
        "0-8": {"type": "w", "letter": "i"},
        "0-9": {"type": "g", "letter": "p"},
        "1-5": {"type": "w", "letter": "m"},
        "1-6": "BLANK",
        "1-7": {"type": "y", "letter": "d"},
        "1-8": "BLANK",
        "1-9": {"type": "y", "letter": "s"},
        "2-5": {"type": "y", "letter": "r"},
        "2-6": {"type": "w", "letter": "e"},
        "2-7": {"type": "g", "letter": "i"},
        "2-8": {"type": "y", "letter": "a"},
        "2-9": {"type": "y", "letter": "a"},
        "3-5": {"type": "g", "letter": "s"},
        "3-6": "BLANK",
        "3-7": {"type": "w", "letter": "s"},
        "3-8": "BLANK",
        "3-9": {"type": "w", "letter": "a"},
        "4-5": {"type": "g", "letter": "s"},
        "4-6": {"type": "w", "letter": "r"},
        "4-7": {"type": "w", "letter": "t"},
        "4-8": {"type": "w", "letter": "s"},
        "4-9": {"type": "g", "letter": "e"},
    },  # Waffle 701
    {
        "0-5": {"type": "g", "letter": "s"},
        "0-6": {"type": "w", "letter": "c"},
        "0-7": {"type": "w", "letter": "g"},
        "0-8": {"type": "w", "letter": "o"},
        "0-9": {"type": "g", "letter": "l"},
        "1-5": {"type": "g", "letter": "n"},
        "1-6": "BLANK",
        "1-7": {"type": "w", "letter": "n"},
        "1-8": "BLANK",
        "1-9": {"type": "y", "letter": "d"},
        "2-5": {"type": "y", "letter": "i"},
        "2-6": {"type": "g", "letter": "n"},
        "2-7": {"type": "g", "letter": "d"},
        "2-8": {"type": "w", "letter": "e"},
        "2-9": {"type": "y", "letter": "e"},
        "3-5": {"type": "w", "letter": "r"},
        "3-6": "BLANK",
        "3-7": {"type": "y", "letter": "i"},
        "3-8": "BLANK",
        "3-9": {"type": "w", "letter": "u"},
        "4-5": {"type": "g", "letter": "f"},
        "4-6": {"type": "w", "letter": "f"},
        "4-7": {"type": "y", "letter": "a"},
        "4-8": {"type": "y", "letter": "r"},
        "4-9": {"type": "g", "letter": "e"},
    },  # Waffle 2
    {
        "0-5": {"type": "g", "letter": "i"},
        "0-6": {"type": "w", "letter": "n"},
        "0-7": {"type": "w", "letter": "c"},
        "0-8": {"type": "w", "letter": "c"},
        "0-9": {"type": "g", "letter": "r"},
        "1-5": {"type": "y", "letter": "e"},
        "1-6": "BLANK",
        "1-7": {"type": "g", "letter": "a"},
        "1-8": "BLANK",
        "1-9": {"type": "y", "letter": "n"},
        "2-5": {"type": "y", "letter": "e"},
        "2-6": {"type": "w", "letter": "e"},
        "2-7": {"type": "g", "letter": "r"},
        "2-8": {"type": "w", "letter": "a"},
        "2-9": {"type": "y", "letter": "s"},
        "3-5": {"type": "w", "letter": "a"},
        "3-6": "BLANK",
        "3-7": {"type": "g", "letter": "v"},
        "3-8": "BLANK",
        "3-9": {"type": "w", "letter": "e"},
        "4-5": {"type": "g", "letter": "t"},
        "4-6": {"type": "w", "letter": "d"},
        "4-7": {"type": "y", "letter": "l"},
        "4-8": {"type": "w", "letter": "i"},
        "4-9": {"type": "g", "letter": "h"},
    },  # Waffle 1070
    {
        "0-5": {"type": "g", "letter": "s"},
        "0-6": {"type": "g", "letter": "p"},
        "0-7": {"type": "g", "letter": "e"},
        "0-8": {"type": "w", "letter": "e"},
        "0-9": {"type": "g", "letter": "d"},
        "1-5": {"type": "w", "letter": "a"},
        "1-6": "BLANK",
        "1-7": {"type": "w", "letter": "t"},
        "1-8": "BLANK",
        "1-9": {"type": "y", "letter": "p"},
        "2-5": {"type": "y", "letter": "t"},
        "2-6": {"type": "w", "letter": "o"},
        "2-7": {"type": "g", "letter": "c"},
        "2-8": {"type": "w", "letter": "i"},
        "2-9": {"type": "y", "letter": "r"},
        "3-5": {"type": "w", "letter": "n"},
        "3-6": "BLANK",
        "3-7": {"type": "g", "letter": "e"},
        "3-8": "BLANK",
        "3-9": {"type": "w", "letter": "m"},
        "4-5": {"type": "g", "letter": "p"},
        "4-6": {"type": "y", "letter": "e"},
        "4-7": {"type": "y", "letter": "i"},
        "4-8": {"type": "w", "letter": "e"},
        "4-9": {"type": "g", "letter": "y"},
    },  # Waffle 3
    {
        "0-5": {"type": "g", "letter": "g"},
        "0-6": {"type": "w", "letter": "n"},
        "0-7": {"type": "y", "letter": "a"},
        "0-8": {"type": "w", "letter": "w"},
        "0-9": {"type": "g", "letter": "t"},
        "1-5": {"type": "g", "letter": "r"},
        "1-6": "BLANK",
        "1-7": {"type": "y", "letter": "o"},
        "1-8": "BLANK",
        "1-9": {"type": "w", "letter": "r"},
        "2-5": {"type": "y", "letter": "a"},
        "2-6": {"type": "y", "letter": "i"},
        "2-7": {"type": "g", "letter": "e"},
        "2-8": {"type": "w", "letter": "p"},
        "2-9": {"type": "w", "letter": "u"},
        "3-5": {"type": "w", "letter": "d"},
        "3-6": "BLANK",
        "3-7": {"type": "g", "letter": "r"},
        "3-8": "BLANK",
        "3-9": {"type": "y", "letter": "a"},
        "4-5": {"type": "g", "letter": "d"},
        "4-6": {"type": "w", "letter": "l"},
        "4-7": {"type": "w", "letter": "o"},
        "4-8": {"type": "y", "letter": "r"},
        "4-9": {"type": "g", "letter": "n"},
    },  # Waffle 1071
    {
        "0-5": {"type": "g", "letter": "p"},
        "0-6": {"type": "w", "letter": "a"},
        "0-7": {"type": "y", "letter": "d"},
        "0-8": {"type": "w", "letter": "g"},
        "0-9": {"type": "g", "letter": "e"},
        "1-5": {"type": "y", "letter": "e"},
        "1-6": "BLANK",
        "1-7": {"type": "g", "letter": "u"},
        "1-8": "BLANK",
        "1-9": {"type": "y", "letter": "a"},
        "2-5": {"type": "y", "letter": "c"},
        "2-6": {"type": "w", "letter": "s"},
        "2-7": {"type": "g", "letter": "c"},
        "2-8": {"type": "w", "letter": "d"},
        "2-9": {"type": "y", "letter": "y"},
        "3-5": {"type": "w", "letter": "v"},
        "3-6": "BLANK",
        "3-7": {"type": "g", "letter": "i"},
        "3-8": "BLANK",
        "3-9": {"type": "w", "letter": "i"},
        "4-5": {"type": "g", "letter": "r"},
        "4-6": {"type": "w", "letter": "u"},
        "4-7": {"type": "y", "letter": "l"},
        "4-8": {"type": "w", "letter": "u"},
        "4-9": {"type": "g", "letter": "e"},
    },  # Waffle 1072
]
