# Daily Waffle grid for testing

test_grid = {
    "0-5": {"type": "g", "letter": "g"},
    "0-6": {"type": "w", "letter": "g"},
    "0-7": {"type": "y", "letter": "s"},
    "0-8": {"type": "w", "letter": "i"},
    "0-9": {"type": "g", "letter": "p"},
    "1-5": {"type": "w", "letter": "m"},
    "1-6": "BLANK",
    "1-7": {"type": "y", "letter": "d"},
    "1-8": "BLANK",
    "1-9": {"type": "y", "letter": "s"},
    "2-5": {"type": "y", "letter": "r"},
    "2-6": {"type": "w", "letter": "e"},
    "2-7": {"type": "g", "letter": "i"},
    "2-8": {"type": "y", "letter": "a"},
    "2-9": {"type": "y", "letter": "a"},
    "3-5": {"type": "g", "letter": "s"},
    "3-6": "BLANK",
    "3-7": {"type": "w", "letter": "s"},
    "3-8": "BLANK",
    "3-9": {"type": "w", "letter": "a"},
    "4-5": {"type": "g", "letter": "s"},
    "4-6": {"type": "w", "letter": "r"},
    "4-7": {"type": "w", "letter": "t"},
    "4-8": {"type": "w", "letter": "s"},
    "4-9": {"type": "g", "letter": "e"},
}
